import type { Track } from './types';

export const DEFAULT_TRACKS: Track[] = [
  {
    id: 0,
    name: 'Kick',
    midiNote: 36,
    mode: 'sample',
    swing: 0,
    volume: 0.8,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 1,
      modulator: 2,
      modulationIndex: 10,
      attack: 0.001,
      decay: 0.2,
      sustain: 0,
      release: 0.3,
      harmonicity: 1,
      volume: -10,
    },
  },
  {
    id: 1,
    name: 'Snare',
    midiNote: 38,
    mode: 'sample',
    swing: 0,
    volume: 0.8,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 2,
      modulator: 3,
      modulationIndex: 8,
      attack: 0.001,
      decay: 0.15,
      sustain: 0,
      release: 0.2,
      harmonicity: 1.5,
      volume: -10,
    },
  },
  {
    id: 2,
    name: 'CHH',
    midiNote: 42,
    mode: 'sample',
    swing: 0,
    volume: 0.6,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 8,
      modulator: 12,
      modulationIndex: 15,
      attack: 0.001,
      decay: 0.05,
      sustain: 0,
      release: 0.05,
      harmonicity: 3,
      volume: -15,
    },
  },
  {
    id: 3,
    name: 'OHH',
    midiNote: 46,
    mode: 'sample',
    swing: 0,
    volume: 0.6,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 8,
      modulator: 12,
      modulationIndex: 12,
      attack: 0.001,
      decay: 0.3,
      sustain: 0,
      release: 0.3,
      harmonicity: 3,
      volume: -15,
    },
  },
  {
    id: 4,
    name: 'Clap',
    midiNote: 39,
    mode: 'sample',
    swing: 0,
    volume: 0.7,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 2,
      modulator: 4,
      modulationIndex: 6,
      attack: 0.001,
      decay: 0.1,
      sustain: 0,
      release: 0.1,
      harmonicity: 2,
      volume: -12,
    },
  },
  {
    id: 5,
    name: 'Rim',
    midiNote: 37,
    mode: 'sample',
    swing: 0,
    volume: 0.7,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 4,
      modulator: 6,
      modulationIndex: 5,
      attack: 0.001,
      decay: 0.05,
      sustain: 0,
      release: 0.05,
      harmonicity: 2.5,
      volume: -12,
    },
  },
  {
    id: 6,
    name: 'Shaker',
    midiNote: 70,
    mode: 'sample',
    swing: 0,
    volume: 0.5,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 10,
      modulator: 15,
      modulationIndex: 20,
      attack: 0.001,
      decay: 0.08,
      sustain: 0,
      release: 0.08,
      harmonicity: 4,
      volume: -18,
    },
  },
  {
    id: 7,
    name: 'Low Tom',
    midiNote: 45,
    mode: 'sample',
    swing: 0,
    volume: 0.7,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 1.5,
      modulator: 2.5,
      modulationIndex: 8,
      attack: 0.001,
      decay: 0.3,
      sustain: 0,
      release: 0.3,
      harmonicity: 1.2,
      volume: -10,
    },
  },
  {
    id: 8,
    name: 'Crash',
    midiNote: 49,
    mode: 'sample',
    swing: 0,
    volume: 0.6,
    mute: false,
    solo: false,
    fmParams: {
      carrier: 12,
      modulator: 18,
      modulationIndex: 25,
      attack: 0.001,
      decay: 1.0,
      sustain: 0,
      release: 1.0,
      harmonicity: 3.5,
      volume: -12,
    },
  },
];
